// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJO_LIKHB6OXA4iDVcthxx5FZQAZkWGos',
    appId: '1:1001006602566:web:555330e190e030bfa42d47',
    messagingSenderId: '1001006602566',
    projectId: 'daily-burn-7ed74',
    authDomain: 'daily-burn-7ed74.firebaseapp.com',
    storageBucket: 'daily-burn-7ed74.firebasestorage.app',
    measurementId: 'G-CCC3VS29SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22bYuTs8XXf2UddUPAhYqZTg-T6m1GAo',
    appId: '1:1001006602566:android:9e2141c842ac6cd7a42d47',
    messagingSenderId: '1001006602566',
    projectId: 'daily-burn-7ed74',
    storageBucket: 'daily-burn-7ed74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-3_IaLWJ76e8VyZ5fJlHm68gnudKF-0',
    appId: '1:1001006602566:ios:625e9809e8b25fbca42d47',
    messagingSenderId: '1001006602566',
    projectId: 'daily-burn-7ed74',
    storageBucket: 'daily-burn-7ed74.firebasestorage.app',
    iosClientId: '1001006602566-emvvuof2jca3ts57ilhf7l1v273sf2tq.apps.googleusercontent.com',
    iosBundleId: 'com.dailyburn.dailyBurn',
  );
}
